//Auto generated by tgf util
//created at 2023-11-22 23:25:10.301815 +0800 CST m=+0.022828680

package errorcodes

const (
	SystemErr int32 = 404

	AccountNotFound int32 = 100001

	ChallengeMapConditionFailed int32 = 200001
)
