//Auto Generated by tgf util,DO NOT EDIT.
//created at 2023-11-22 23:25:10.296926 +0800 CST m=+0.017935052

package conf

type ConstantConf struct {

	//键
	Key string

	//值
	Value string

	//描述
	Desc string
}

type PropConf struct {

	//唯一id
	Id string

	//类别id
	StyleId string

	//道具名称
	Name string

	//效果类型
	EffectType string

	//效果参数
	EffectValues []string

	//描述
	Desc string
}

type ErrorCodeConf struct {

	//错误码
	Code int32

	//文字
	Message string

	//字段名
	FieldName string

	//描述
	Desc string
}
